name: Build MusicBot Docker Image

on:
  workflow_dispatch:
    inputs:
      musicbot_version:
        description: 'Jagrosh/MusicBot version (required) Ex-0.3.9'
        required: true
        default: '0.3.9'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: swatre/jmusicbot:latest
