name: Build MusicBot Docker Image

on:
  workflow_dispatch:
    inputs:
      musicbot_version:
        description: 'Jagrosh/MusicBot version (required) Ex-0.3.9'
        required: true
        default: '0.3.9'

jobs:
  Build-Push-Docker-Image:
    runs-on: ubuntu-latest
    env:
      musicbot_version: ${{ github.event.inputs.musicbot_version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Building Docker Image
        run: |
          echo ${musicbot_version}
          docker build --build-arg MUSICBOT_VERSION=${musicbot_version} -t ${{ secrets.DOCKERHUB_USERNAME }}/jmusicbot:${musicbot_version} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jmusicbot:${musicbot_version}
